language: python
python:
  - "3.6"
  - "3.7"
install: pip install -r requirements.txt

script:
  - ls 
  - python py_mortgage/tests.py
  - python -m pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "ulc5BI3cq1xrWG+7S4oPcJYSua2KEJtfzqt3y07WOy8pe8p/jSXyvtajvD2nKen5td93Mud/VsyoRV/M2R2tDAWbr4zlBJDBGimnF/VgbC7yIe4a/aDZ92IKzXhEqFXu3Wf4+sTZDT83DsUlvJ2ed7PUNP6AAxuur3Ozt6GEwReYWFmV9cFYQm4D/x7hvFQGDW02VRabRPm0kCY4VjYwgMbMidMmMCf/mj09kdddIzSfDvzzzTALmu5zmc9OwBiJ9sSZkOUI0FgJJvEemP6bJDiuDwBGiEs+89Nh1h+kE3nV1Zmvr0ja/Uz/bo3yBEZDYFpCcI1KJepX9Rs+1BX88XdrIpSlwf9EMci38FrRyJSot9AiZszNPdg3KSOXB6+rH3gF1feOGZiM0e8GEoxWeX+qTv3L7w14WsEyRbDNDl/s1kFXXcbI0HpGbg3vf9COJVWWOZdVNyavMaUrALf+PchPSeLUOTPo2b720GvTPLpoN/COVLa8F2ZvKkIQVGABgMngY4KeQ8Jc1P7BFWPENrMSjAl/S3DlqryHu+8YBBxpbp2Oiw1mrnn8FTL/uaixXwbOP76X3iQEkkSRi20Fc70bK3T1DcFR12M1TDfLhi/ZISpE5KamtBWNJ7xkSRwpZFUFC4pq/PLe46XXP63K54y2JnNixMyzF/NnkBJDflk="
  distributions: "sdist bdist_wheel"
  on:
    branch: master