language: python
python:
- '3.7'
install: pip install -r requirements.txt
script:
- ls
- python py_mortgage/tests.py
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: ${SECURE_KEY}
  distributions: sdist bdist_wheel
  on:
    branch: master
